DROP TABLE REGISTERED_USERS;
DROP TABLE PLAYS_FOR;
DROP TABLE TOURNAMENT;
DROP TABLE GAME;
DROP TABLE TEAM;
DROP TABLE PLAYER;

--Players and teams part of the database
CREATE TABLE PLAYER
(
    PLAYERID            VARCHAR2(30),
    FNAME               VARCHAR2(30),
    LNAME               VARCHAR2(30),
    COUNTRY             VARCHAR2(30),
    AGE                 NUMBER(2),
    YEARS_PRO           NUMBER(2),
    TOURNAMENT_WINS     NUMBER(4),
    IMAGE_RESOURCE_ID   NUMBER(20),
    CONSTRAINT PLAYER_PRIMARY_KEY PRIMARY KEY (PLAYERID)
);

CREATE TABLE TEAM
(
    TEAMID              VARCHAR2(30),
    NAME                VARCHAR2(30),
    COUNTRY             VARCHAR2(30),
    YEARS_PRO           NUMBER(2),
    MONEY_WON           NUMBER(14,2),
    MANAGERID           VARCHAR2(30),
    CONSTRAINT TEAM_FOREIGN_KEY FOREIGN KEY (MANAGERID) REFERENCES PLAYER(PLAYERID),
    CONSTRAINT TEAM_PRIMARY_KEY PRIMARY KEY (TEAMID)
);

CREATE TABLE GAME
(
    GAMEID              VARCHAR2(30),
    NAME                VARCHAR2(30),
    YEARS_PLAYED        NUMBER(2),
    CONSTRAINT GAME_PRIMARY_KEY PRIMARY KEY (GAMEID)
);

CREATE TABLE TOURNAMENT
(
    TOURNAMENT_ID       VARCHAR2(30),
    DAY                 VARCHAR2(30),
    GAMEID              VARCHAR2(30),
    WINNER              VARCHAR2(30),
    CONSTRAINT TOURNAMENT_PRIMARY_KEY PRIMARY KEY (TOURNAMENT_ID),
    CONSTRAINT TOURNAMENT_GAME_FOREIGN_KEY FOREIGN KEY (GAMEID) REFERENCES GAME(GAMEID),
    CONSTRAINT TOURNAMENT_TEAM_FOREIGN_KEY FOREIGN KEY (WINNER) REFERENCES TEAM(TEAMID)
);

CREATE TABLE PLAYS_FOR(
    PLAYERID            VARCHAR2(30),
    TEAMID              VARCHAR2(30),
    CONSTRAINT PLAYS_FOR_PRIMARY_KEY PRIMARY KEY (PLAYERID,TEAMID),
    CONSTRAINT PLAYS_FOR_PLAYERID_FOREIGN_KEY FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID),
    CONSTRAINT PLAYS_FOR_TEAMID_FOREIGN_KEY FOREIGN KEY (TEAMID) REFERENCES TEAM(TEAMID)
);

--For the users of the Database
CREATE TABLE REGISTERED_USERS
(
    USERID              VARCHAR2(30),
    PASSWORD            VARCHAR2(30),
    CONSTRAINT REGISTERED_USERS_PRIMARY_KEY PRIMARY KEY (USERID)
);